#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=24
#SBATCH --time=0:10:00
#SBATCH --mail-type=FAIL,BEGIN,END
#SBATCH --output=out.log
#SBATCH --error=err.log
#SBATCH --job-name=jobName

# below are the modules you will need to compile the code on bigred3 (see README)
######  Module commands #####
module swap PrgEnv-intel PrgEnv-gnu
module load boost/gnu
module load gsl

cd $SLURM_SUBMIT_DIR

export OMP_NUM_THREADS=24

# the following is a test simulation to check things are working, it simulates 0.1 M of +1 and -1 ions of diameter 0.714 nm confined within 3 nm
# -d refers to number of cores. this should match ppn in Line 2.
time srun -n 1 -d 24 ./md_simulation_confined_ions -Z USER-Z-USER -p USER-p-USER -n USER-n-USER -c USER-c-USER -d USER-d-USER -a USER-a-USER -i USER-i-USER -S 100000 -B 0.05
